Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/07/2019
Var
// Seção de Declarações das variáveis 

num1: inteiro
num2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva (" Digite um numero: ")
leia (num1)

escreva (" Digite outro numero: ")
leia (num2)

escreval (" O resultado de " ,num1, " + " ,num2, " = " ,num1+num2)

Fimalgoritmo