Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/07/2019
Var

ImparPar: inteiro
resultado: caracter

Inicio

escreva(" Digite um numero Impar ou Par! ")

leia(ImparPar)
se(ImparPar mod 2 = 0) entao   // mod é um operador matemático(operador lógoco)
escreval(" O numero " ,ImparPar, " é PAR! ")

senao
escreval(" O numero " ,ImparPar, " é IMPAR! ")

fimse

Fimalgoritmo